name: ipython-notebook
dependencies:
  - notebook
  - requests
  # get dependencies for pgcontents
  - certifi
  - click
  - mako
  - psycopg2
  - six
  - sqlalchemy
  - pip:
  #  - pgcontents
    - git+git://github.com/p-a-c-o/pgcontents.git
