name: ipython-notebook
dependencies:
  - notebook
#  - ipywidgets
#  - requests
  # get dependencies for pgcontents
#  - certifi
#  - click
#  - mako
#  - psycopg2
#  - six
#  - sqlalchemy
#  - nose
  # get dependencies for extensions
  - psutil
  - pip:
#    - git+git://github.com/pl31/pgcontents.git
#    - git+git://github.com/ipython-contrib/IPython-notebook-extensions.git
    - python-contrib-nbextensions
